/*
  FILE GENERATED BY src/misc/writeBuildNum.sh
               *** DO NOT EDIT ***
  TO CHANGE ANY INFORMATION IN HERE PLEASE
  EDIT src/misc/writeBuildNum.sh
  FORMAL BUILD NUMBER:1268
*/

#define PRODUCT_VER_STRING "5.0.0.1268"
#define FILE_VER_STRING "WI-V5.0.0.1268"
#define LICENSE_VER_STRING "WI-V5.0.0.1268"
#define FILE_VER_NUMBER 5, 0, 0, 1268
#define FB_MAJOR_VER "5"
#define FB_MINOR_VER "0"
#define FB_REV_NO "0"
#define FB_BUILD_NO "1268"
#define FB_BUILD_TYPE "V"
#define FB_BUILD_SUFFIX "Firebird 5.0 RC 2"
