/*
  FILE GENERATED BY src/misc/writeBuildNum.sh
               *** DO NOT EDIT ***
  TO CHANGE ANY INFORMATION IN HERE PLEASE
  EDIT src/misc/writeBuildNum.sh
  FORMAL BUILD NUMBER:446
*/

#define PRODUCT_VER_STRING "6.0.0.446"
#define FILE_VER_STRING "WI-T6.0.0.446"
#define LICENSE_VER_STRING "WI-T6.0.0.446"
#define FILE_VER_NUMBER 6, 0, 0, 446
#define FB_MAJOR_VER "6"
#define FB_MINOR_VER "0"
#define FB_REV_NO "0"
#define FB_BUILD_NO "446"
#define FB_BUILD_TYPE "T"
#define FB_BUILD_SUFFIX "Firebird 6.0 Initial"
